logging:
  path: ./logs

server:
  port: ${PORT:5007}

spring:
  cloud:
    consul:
      discovery:
        tags: traefik.frontend.rule=PathPrefixStrip:/queue/api
  kafka:
    bootstrap-servers: ${BOOTSTRAP_SERVERS:localhost:9092,localhost:9093,localhost:9094}
    producer:
      retries: 3
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer